application: drexelschedules
version: 1
runtime: php
api_version: 1

handlers:
- url: /simple_html_dom.php
  script: simple_html_dom.php

# serve php scripts
- url: /(.+\.php)$
  script: \1

- url: /(.+\.js)$
  script: \1

- url: /.*
  script: index.php
